DickinsonCollege/FarmData2

CONTRIBUTING.md
Fix the link to the Issue Tracker in file CONTRIBUTING.md (closes #33)
---
=> Fix the link to Issue Tracker in CONTRIBUTING.md

CONTRIBUTING.md
Fixed Issue 33 by switching out the hyperlink for the 'Issue Tracker' link to the URL for the issue track tab on the DickinsonCollege/FarmData2 repository.
---
=> Fixed Issue #33

CONTRIBUTING.md
I changed to the correct link for the issue #33 in CONTRIBUTING.md
---
=> Change to correct link

CONTRIBUTING.md
This will add a link to a github webpage that shows a user how to clone a project. This is helpful so that a new contributor can have better info on how to contribute. This link will be close to the end of the page, and will be located with the word "Clone".
---
=> adding link to Clone

CODE_OF_CONDUCT.md
In the file CODE_OF_CONDUCT.md I changed the phrase "body size" to "body type" in order to use a more umbrella term when talking about inclusivity.
---
=> changed phrase "body size" to "body type: in code of conduct

INSTALL.md
Running VirtualBox on Retina display on mac can cause it to be very slow.  Added to INSTALL documentation a link to how to run VirtualBox in low resolution mode, which solves the problem.
---
=> Added fix for slow retina display on mac.

CONTRIBUTING.md
Add links for Zulip community for discussing bugs and/or features as an option in addition to filing a ticket in the issue tracker.
---
=> Added link to Zulip for bugs/features

docker/docker-compose.yml
Fixed the image name of the Theia container that is built so that it is fd2_theiaide to match the others.
---
=> Fixed theia container name

docker/docker-compose.yml, docker/farmOS/Dockerfile, docker/farmOS/ability_to_filter_with-1910294.patch, docker/fd2-up.bash, docker/theia/Dockerfile
The restws module in Drupal did not allow filtering of results with >, <, >=, <= etc... This was problematic for selecting logs with a range of dates (e.g. for reports).  The patch at: https://www.drupal.org/project/restws/issues/1910294 modifies the restws module to provide this functionality.  Though that patch had what appeared to be typo that was fixed in the local .patch file now in the docker/farmOS directory.  In addition, there were a few changes made to the Docker file for theia, the docker-compose.yml file.
The docker-compose.yml file now uses fd2.<ver> number for the custom built images so that we can force them to be rebuilt on developer machines if necessary.
---
FarmData2 is a [Free Cultural …
=> Built custom FarmOS image with restws patch for filtering

docker/fd2-up.bash
Added a step in the fd2-up.bash script that clears the drupal cache.  This will ensure that anytime a new image is produced that all of the modules are reloaded.  Issues with out this would be rare, but this prevents them.
---
=> Added clear cache to fd2-up.bash

docker/farmOS/restws.entity.inc
The $operation variable was undefined here so commented it out to remove that error.  This seems to be working for now.  But it may be that this causes other errors in FarmOS that I haven't seen yet.  What needs to happen is to go back to the original version of the restws.entity.inc file and see where the $operation variable was getting set and then see if a more complete fix can be made. 
--- …
=> Removed line with undefined variable.

docker/updatepassword.sh
This script allows a user to change the passwords of the drupal admin account, the farmdata2db account in the database, and the root account of the database.  It also changes the settings file to allow drupal to continue to talk to the database with the new password.  
Closes #42 
---
=> password inititalization

farmdata2_modules/fd2_tabs/fd2_barn_kit/fd2_barn_kit.module
Reorders the reporting tabs under the BarnKit tabs so that info is on the left and the others appear in a defined order after that.  This was done by setting the weights given  that lower (more negative weights) appear further to the left.
---
=> Reordered BarnKit tabs

docker/cypress/Dockerfile, farmdata2_modules/test_runner.bash
To run tests in cypress that use axios it was necessary to have axios installed in the container using npm so that it was available to the tests.
---
=> Added axios to the cypress test runner docker image.

farmdata2_modules/cypress.json, farmdata2_modules/fd2_tabs/resources/FarmOSAPI.js, farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js, farmdata2_modules/fd2_tabs/resources/farmOSAPI.spec.js
Adds the getAllPages function in the farmdata2_modules/resources/farmOSAPI.js file.  Given a URL and an array, the function fills the array with the values from the response.data.list from every page in a multipage response.
@Co-authored-by: josiecook <cookjo@dickinson.edu>
---
=> Fetch all pages

farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js
Several tests in the FarmOSAPI.spec.js contained .only flags so not all tests would run.  This removed those so all tests now run.
---
=> Removed .only on tests

farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js
The getAllPages test for multiple pages used a wait where it should have been a get and also included an extraneous ) in the wait for the alias.  A few other small changes were made.  function's were used only where there is a need for the this object in the test, otherwise the () => {} notation was used.  Also removed some stray .only's in the test spec so that all tests will run.
--- …
=> Fixed getAllPages test using get and proper alias

docker/sampleDB/buildSampleDB.bash
The script that builds the sample database (docker/buildSampleDB.bash) now also sets the farm name to "Sample" and the slogan to indicate that it is a sample farm for testing and development.
---
=> Updated script to set farm name and slogan

INSTALL.md
GitHub as of August 13, 2021 will require the use of a personal access token for connection via the git command line tools.  This PR updates the INSTALL.md document to include a pointer to instructions about creating a personal access token and caching it in the git credential helper.
Closes #71
---
=> Updated INSTALL.md for access token requirement

docker/sampleDB/README.md, docker/sampleDB/addCrops.py, docker/sampleDB/addDirectSeedings.py, docker/sampleDB/addTraySeedings.py, docker/sampleDB/buildSampleDB.bash, docker/sampleDB/sampleData/crops.csv, docker/sampleDB/utils.py
There were duplicate crop names (e.g. DRY was both under BEANS and CORN).  This created problems mapping from crop name to cropID.  So converted to using compound crop named (e.g. BEANS-DRY and CORN-DRY).  
Also added the cropID to the data field of the plantings to make it possible to find the crop vocabulary term without fetching the Planting.
---
=> Updates the Names of Crops (e.g. ONION-SPRING)

docker/sampleDB/addTransplantings.py
A number of transplantings in the sample data from FarmData have a seeding date of 0000-00-00 indicating that there was no seeding to connect to.  This could be because the plants arrived in a tray or because a seeding was just never created.  This update uses the transplanting date to create a planting for the transplanting.
---
=> Translate 0000-00-00 Transplantings

docker/cypress/Dockerfile
As apt packages were modified by others this began generating errors.
Becasue this is a dev only container we'll leave everything fixed
at the versions in the base container to prevent future errors. Everything
can be moved to newer versions all at once when necessary.
---
=> Removed apt update from Cypress Dockerfile

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js
The loading spinner that appears when the "Generate Report" button is clicked, now reappears when it is clicked more times. 
Closes #272 
Closes #270 
---
=> Spinner reappear

farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
=> Updated comment

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js, farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.js, farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.spec.comp.js, farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.js, farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.spec.comp.js
This should resolve #274.
It should:
- change the timing of the report disappearing to when the input is clicked 
---
=> New date change report timing

docker/theia/Dockerfile
The theiaide/theia:1.7.0 image was removed from theiaide on Docker Hub.  So a new account was created for farmdata2 and the theia:1.7.0 image was placed there.  This is a temporary solution and a more permanent solution should be found.  Most likely, farmdata2 should move to a VS Code container instead of theia.  That is a bigger move than can be done right now so this stop gap will suffice for now.
--- …
=> Moved theia docker image to farmdata2 dockerhub

farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js, farmdata2_modules/fd2_tabs/resources/CustomTableComponent.spec.comp.js
Missed a line when refactoring the tests that caused some parse errors trying to convert a string to a number.  Just removed that line.
---
=> Removed missed line causing parse errors

docker/sampleDB/README.md, docker/sampleDB/addHarvests.py, docker/sampleDB/addTransplantings.py
Added this object to the transplanting logs and the
harvest logs. This makes it possible to get the crop name
from the tid without retrieving the associated planting.
Also regenerated the sample database to include this
object in the logs.
---
=> Add data object with crop_tid info.

docker/docker-compose.yml, docker/farmOS/Dockerfile
farmos pushed a new dev instance of the farmos/farmos:dev image to dockerhub.  This broke the FarmData2 install process because of some changes contained in that image.  This patch freezes the farmos image being used by using our own copy of the farmos image that has been pushed to farmdata2/farmos on dockerhub.
The farmdata2/farmos image will be pulled and customized normally for new installs.  For existing installs the farmdata2/farmos image will be pulled and customized the first time a developer uses ./fd2-up.bash after pulling these changes from upstream main.
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This …
=> Switched farmos image to farmdata2/farmos on DockerHub

LICENSE.md
Fixed broken link of authors.md as reported in:
https://github.com/DickinsonCollege/FarmData2/issues/335
---
=> Issue 335: Fixed broken link in License.md>Attributes section

ONBOARDING.md
FarmOS moved to a new version of their API.  For now FarmData2 is still using V1 of the API.  This update ensures that our documentation points to the proper version of of FarmOS's API docs.
---
=> Updated FarmOS API Links

farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
Fixes #460 
Modified the way the cached areas are updated.  When there were cached areas, an API call was made to check for updates and then the cached list was to be updated with the response. However, the response was being appended instead of replacing the existing list.  It now replaces it and updates the displayed list of areas also.
---
=> Eliminates duplicate areas in drop down

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
Fixes #260 Deleted HTML component and the function under computed that correspond to the display and calculation of Total Bed/Row under the summary section for direct seeding. No changes were made to the cypress file as it did not include any total bed/row related test methods. 
---
=> Issue260: delete total row/bed planted from summary section for direct seeding in the Seeding Report

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
Resolves #332. Addresses the unsorted seeding report where direct seeding logs would appear before transplanting logs, disregarding the dates of the logs. Added some code in the tableRows() that uses built-in JavaScript sort to sort the rows by date before returning the rows array to be displayed on the table.
---
=> Issue332: Sorted seeding report by dates in ascending order

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html
Resolves #464. Removed unnecessary words from summary blocks. Removed 'per' and replaced it with a '/'. Made average rows/hour and bed/hour planted in direct seeding summary consistent with listing of rows and beds feet planted above.
---
=> Summary Table Edits

farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.js
The DropdownWithAllComponent Vue component was defined as a div element. This created difficulties with layouts where the dropdown was to be inline with other text or elements (e.g. in the Seeding Input form).  Changing this to a span allows the dropdown to be inline when desired.
---
=> Changed DropdownWithAllComponent from div to span element

farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.js, farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.js
Changed the DateSelectionComponent to be a span element instead of a div element.  Updated the DateRangeSelectionComponent to add a line break between the two DateSelectionComponents because they are now span elements. 
---
=> Change div to span in components

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html
Resolves #476. This pull request changes how the Seeding Report calculates the hours column. Marcel's P.R actually changes the structure of  'Labor' in the Seeding Input Log to make this change more clear.
---
=> Time Reporting: Computes Hours Differently in Seeding Report

.gitignore, farmdata2_modules/fd2_tabs/resources/JSDoc.json, farmdata2_modules/fd2_tabs/resources/README.md
Make the installation of JSDoc using npm local instead of global on the system.  This resolves an issue with use on machines that install the node_modules into different locations globally.
Closes #483 
---
=> Made JSDoc install local rather than global

farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
There was a '(s)' missing in Seeding Input Form in the Worker's For Label.
---
=> Fixed 'Seeding Input: Labor Section Text Missing Plural'

docker/docker-compose.yml
The fd2_phpmyadmin container was restarting when the VM was shutdown and restarted.  This was inconsistent with the behavior of the other containers.  No no containers are restarted automatically.
Fixes #329 
---
=> Removed restart always for fd2_phpmyadmin container.

farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.js
Removed a leftover symbol from the *DateRangeSelection's* template that was being rendered into the page. 
---
=> DateRangeSelection: Removed leftover symbol inside template.

farmdata2_modules/fd2_tabs/fd2_example/ui.html, farmdata2_modules/fd2_tabs/fd2_example/ui.spec.js, farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js, farmdata2_modules/fd2_tabs/resources/CustomTableComponent.spec.comp.js
Fixes #357. Added two buttons to show and hide columns for the CustomTableComponent on the ui.html page. Added Cypress test to fix the issue. Also fixed minor syntax issues in CustomTableComponent and the test file. 
---
=> Issue #357: Add buttons to test hide show column for CustomTableComponent

farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html, farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.spec.js
Solves #510.  Added some simple JavaScript that scrolls to the top of the page once the user hits the confirm or cancel button. 
---
=> Seeding Input: Auto Scrolls to Banners at the Top of Page

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js, farmdata2_modules/fd2_tabs/fd2_example/ui.html, farmdata2_modules/fd2_tabs/fd2_example/ui.spec.js, farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html, farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.spec.js
This PR aims to solve #360 by implementing a standard for pages to handle API request failures. 
When an API request fails, a banner will appear on the top of the page to indicate to the user that an API request has failed and to attempt to revisit the page shortly. 
**Note: This PR is ready to be merged into upstream**
The following steps must be completed before this PR is ready for review:
--- …
=> Implementing Standard Error Handling for API Request Failures

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html, farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js
Fixes #520 . Added configuration feature to the seeding Report. Hides hour, worker column if the labor config is set to hidden. The summary table also hides average hour and total hour if the labor config is set to hidden. 
---
=> Issue520 Configuration Integration to Seeding Report

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js
Just a quick PR to remove this only inside the Cypress test. 
---
=> Removing Lingering Only Inside Seeding Report Test

farmdata2_modules/fd2_tabs/fd2_barn_kit/fd2_barn_kit.module, farmdata2_modules/fd2_tabs/fd2_barn_kit/transplantingReport.html, farmdata2_modules/fd2_tabs/fd2_barn_kit/transplantingReport.spec.js
Closes #415. This PR adds the Transplanting Report sub-tab to the Barn Kit module. It's functionality is very similar to the Seeding Report but simpler because we're only dealing with transplanting logs instead of two types of seedings. 
These issues must be addressed prior to review for merge into upstream: 
---
=> Addition of a Transplanting Report

farmdata2_modules/fd2_tabs/fd2_config/fd2_config.module
Fixes #553. Fixed typo which fixed the issue. The token in the database failed to match the label because it was declared as "labor" instead of "label. 
---
=> Issue #553 FD2 Configuration Module Drupal Error

farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js
Removes a lingering only inside of the FarmOSAPI test file. 
---
=> FarmOSAPI: Remove Only in Cypress Test

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html
Closes #574. Fixed a simple miscalculation for the Row Feet/Hours in the direct summary of the Seeding Report. Th e2e test remains unchanged because it will be addressed in another issue.
---
=> Fixed Average Row Feet/Hour Calculation

INSTALL.md, docker/README.md, docker/fd2-down.bash
Updates fd2-down.bash to remove the dev container when FarmData2 is shut down.  There was an issue when running in WSL that is addressed by this fix.  The fix is a little unsatisfactory in that the writeable later in the dev container is lost.  Thus, any local installs done are lost when FarmData2 is taken down.  If this presents a challenge for lots of developers then this issue should be revisited.
This closes #584.
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate …
=> Updated fd2-down.bash to remove dev container.

.gitignore, farmdata2/farmdata2_modules/fd2_example/ui/ui.html, farmdata2/farmdata2_modules/fd2_example/ui/ui.table.spec.js, farmdata2/farmdata2_modules/resources/CustomTableComponent.js, farmdata2/farmdata2_modules/resources/CustomTableComponent.spec.comp.js
This PR adds the id of the row being edited in the CustomTableComponent to the `edit-clicked` event.  It makes corresponding changes in the unit tests for the component and in the UI example page and its tests.
---
=> Added id to PayLoad of CustomTable edit-clicked event

farmdata2/farmdata2_modules/fd2_example/ui/ui.table.spec.js, farmdata2/farmdata2_modules/resources/CustomTableComponent.js, farmdata2/farmdata2_modules/resources/CustomTableComponent.spec.comp.js
The CustomTableComponent `data-cy` attributes for input elements did not uniquely identify the input element.  In particular, if two elements had the same type of input they would have had the same `data-cy` attribute value.  They now have the value `ri-columnHeader-input` where the `columnHeader` is the header of their column in the table.  This matches what is done for cells when the table is not in edit mode.
--- …
=> Clarified and fixed CustomTable data-cy attributes for input elements

farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.html, farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.spec.js, farmdata2/farmdata2_modules/fd2_barn_kit/transplantingReport/transplantingReport.html, farmdata2/farmdata2_modules/fd2_barn_kit/transplantingReport/transplantingReport.spec.js, farmdata2/farmdata2_modules/fd2_example/cache/cache.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html
The pageLoaded pattern has been applied to the barnKit and fieldKit pages.  This pattern places a hidden element in the page that has its value set to true when all of the API calls in the `created` method have completed. This is used in testing to ensure that the page has fully loaded before the tests are run. 
This is important because when pages are loading information in the `created` method, fast running tests were completing and the next test was starting before those API requests had completed or even been initiated.  This was generating flakiness in the test suite.  It would run fine one time and not the next.  Waiting for the page to load introduces delays, but removes the flakiness.
---
FarmData2 is a [Free Cultural …
=> Added the pageLoaded pattern to barnKit and fieldKit

farmdata2/farmdata2_modules/resources/CustomTableComponent.js, farmdata2/farmdata2_modules/resources/CustomTableComponent.spec.comp.js
Closes #599. This PR adds a computed property to the `CustomTableComponent.js` to remove the multiple locations in the template checking when to make the selection bar appear in the table. Because it would be easy to miss these locations when adding new button cases, this computed method serves as a general locations for adding this button locations without worrying about making changes to the template.
Because this doesn't alter functionality, no additional testing was added. However, the table's unit test was updated because the Cypress tests for the CSV download broke with the reorganization of the project. The path is currently fixed. This is fine because the structure of the project doesn't change frequently but should we consider putting more resources …
=> Encapsulating Button Cases for the CustomTableComponent

farmdata2/farmdata2_modules/fd2_barn_kit/fd2_barn_kit.module, farmdata2/farmdata2_modules/fd2_config/fd2_config.module, farmdata2/farmdata2_modules/fd2_example/fd2_example.module, farmdata2/farmdata2_modules/fd2_field_kit/fd2_field_kit.module, farmdata2/farmdata2_modules/fd2_school/fd2_school.module
Closes #565. Adds a simple simple `@` in front of the cmd command that maps the user ID's and names as a preprocessing function. This error would appear when users attempted to access a page without being logged into the page. The warning no longer appears due to this surpression and a comment explaining the `@` placement is now present in the module files. 
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its …
=> Surpressing Standard Name Error

farmdata2/farmdata2_modules/fd2_example/dbtest/dbtest.get.seedings.spec.js, farmdata2/farmdata2_modules/fd2_example/dbtest/dbtest.html, farmdata2/farmdata2_modules/fd2_example/dbtest/dbtest.maps.spec.js, farmdata2/farmdata2_modules/fd2_example/dbtest/dbtest.modify.seedings.spec.js, farmdata2/farmdata2_modules/fd2_example/dbtest/dbtest.sessionToken.spec.js, farmdata2/farmdata2_modules/fd2_example/fd2_example.module, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.labor.defaults.spec.js, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.type.defaults.spec.js
Modified the `dbtest` examples so that they use the `cy.waitForPage()` pattern that will be typical of real use cases.
---
=> Db test waits

docker/dev/Dockerfile, docker/dev/repo.txt, docker/docker-compose.yml, farmdata2/cypress/support/component.js
Builds on #649, see that PR for additional information.
---
=> Add Bootstrap support to Vue Component Tests

farmdata2/farmdata2_modules/fd2_field_kit/cypress/fieldkit.tab.spec.js
* Created txt file for initialize branch
* Created epr1.md
* deleted created_branch.txt
* Revised EPR1
* cypress file created for fieldkit sub-tab
* beforeEach added for login in farmdata2 web
* changed url for beforeEach and sub-task1 finished
* finished sub-task 1
* Checks that the order of the tabs is “Info” and then “Seeding Input.”
* ignore this commit
* Revert "deleted created_branch.txt"
This reverts commit fff6611033b011469f6543c3964db1433d084306.
* Implemented a test that checks the correct number of sub-tabs
* Removed create_branch.txt and reports directory.
* Verifies that the number of sub- tabs is exactly 2 and adds a general comment at the top of the file
Co-authored-by: won369369 <wj0293@gmail.com>
Co-authored-by: Shahir-47 <ahmeds@dickinson.edu>
---------
__Pull Request …
=> Migrates: FieldKit Tab: Test for FieldKit Sub-Tabs  (#212)

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
* add tray selection test
* add area dropdown test
* Adding test for seeding field and trays field
* Write tests for area dropdown and cells/tray field in Tray Seeding Input
* reformat the tests and add test no area is selected by default
* Fixing test for input value
* fix testing on tray seeding input
* reformat the test and modify the test dropdown area
* Reformat Testing tray and seed fields
* add blank line and test enable
Co-authored-by: nguyenbanhducA1K51 <ducnguyen.wings@gmail.com>
Co-authored-by: phong260702 <phongdangquoc123@gmail.com>
---------
This pull request was originally created on [FD2School-FarmData2](https://github.com/DickinsonCollege/FD2School-FarmData2).
Link to the original pull request: …
=> Migrates: Testing Seeding Input Tray Seeding Defaults (#194)

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.misc.defaults.spec.js
* Create test file for the Seeding Input
* Test the comment box
* test for HaTest
* added page heade
* tested to check that submit button is disabled
* Test for Submit button
* Add test the comment box is enable and the submit button is labeled
* Tested to check that SUBMIT button is disabled
* solved merge conflict
* modified page header test
* added label comment
* Fix type error for testing the submit button is enabled
* edit space between it() block to have consistent spacing
* Add comment to give the purpose of the test file
* Fix the test for the section with label Comments
Co-authored-by: vuphuongha <havu0910@gmail.com>
Co-authored-by: ha vu <60118892+vuphuongha@users.noreply.github.com>
Co-authored-by: tainguyen103 <tainguyen103200@gmail.com>
--------- …
=> Migrates: Create test file for the Seeding Input (#211)

farmdata2/farmdata2_modules/fd2_barn_kit/cypress/barnkitTab.spec.js
* Initial commit for BarnKit tab testing
* Tested the BarnKit tab contains the 3 sub-tabs
* Added the Second test and initiated the third test of the barnkitTab.spec.js
* Testing on proper branch
* Revised test for BarnKit subtabs ordering and length
* Delete transplantingReport.defaults.spec.js
* Revised the test for checking number of subtabs
* Resolved issues and committed final changes
Signed-off-by: Udval Enkhtaivan <74579865+udvale@users.noreply.github.com>
Co-authored-by: thorpIV <thorpg@dickinson.edu>
Co-authored-by: aliouas <aliouas@dickinson.edu>
---------
Link to the original pull request: …
=> Migrates: BarnKit Subtab testing (#219)

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.direct.defaults.spec.js
* Created txt file for initialize branch
* testing commit on feature branch
* SeedingInput cypress file created
* Tests must check that the Direct Seeding section of the Seeding Input Form appears when "Direct" is selected
* deleted create_branch.txt
* cypress test name changed
* Test that it displays dropdown for units
* comment for numbering sub-task 6 added
* test for dropdown area
* Reviewed Gyujin's solution to sub-task 3, 7
* checks that there is a field for Row/Bed that is empty and enabled
* checks that there is a field for Bed Feed that is empty and enabled
* checks that Bed Feet is the default units
* rearranged the order of each sub-test
* changed cypress file name
* changed correct cypress file name
* resolved all conversations from prof. braught
* added comments to each …
=> Migrates: Test Seeding Input Direct Seeding Defaults (#182)

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.labor.defaults.spec.js
* added spec.js file
* Added it block for testing header
* checked the number of workers field is empty and enabled
* checked the number of time worked field is empty and enabled
* Added the "check correct dropdown for selected time unit" "Checks Time units dropdown"
"checks time units default is minutes"
* couple of spacing and alignment issues fixed.
* changed a test name to be more descriptive
Signed-off-by: Foogabob <80643562+Foogabob@users.noreply.github.com>
Co-authored-by: EliasBerhe <eliastes123@gmail.com>
Co-authored-by: Foogabob <locker@dickinson.edu>
Co-authored-by: Foogabob <80643562+Foogabob@users.noreply.github.com>
--------- …
=> Migrates: Cypress Tests for Seeding Input Labor Defaults (#173)

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html, farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.type.defaults.spec.js
* created file to test seeding input type defaults
* Filled out before each
* Our team's test shows up in correct folder so we can run in Cypress
* Added test to check if the Tray element is enabled
* Added test to check if the Direct element is enabled
* tested that neither the tray nor the direct element is selected
* tested whether the message to prompt tray/direct element selection is visible
* Tested that the form elements for Tray and Direct are not visible
* Finished testing visibility of form elements - had to add one more
* Deleted unnecessary (duplicate) test file from field kit
* Adjusted the comment in the describe and added a descriptive comment at the top of the file.
* merged second and third individual test into one test
* changed data-cy attribute of message to prompt …
=> Migrates: Tested Seeding Input Type Defaults (#178)

farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.html
This PR changes the `selected-val` of the Seeding Type Dropdown from 'All' to the `getDefaultSeedingSelection` function that returns the appropriate seeding type for the available logs.
Closes #658 
---
=> Change default seeding type according to existing logs

docker/build-images.bash
This PR aims to close/resolve #636 by adding a local flag to `docker/buildimages.bash`. Also made some slight changes (local builds use `build` insted of `buildx` for local builds and only multi-arch build use `fd2builder`)
=> Add Local flag to docker/buildimages.bash

farmdata2/cypress/cypress.config.js
close #686
This add small feature to help log information such as request and response to terminal when using cypress test in headless mode . To log information, use command cy.task( "log", <data>) to print to terminal.
---
=> Add  cypress logging functionality

docker/fd2-down.bash, docker/fd2-up.bash
The `COMPOSE_PROFILE` environment variable was not working on MacOS.  So reverted the `fd2-down.bash` script to use the `stop` and `delete` commands instead.
---
=> revert changes to fd2-down.bash to work on MacOS too
