CONTRIBUTING.md

I fixed issue #33 by changing the link for issue tracker to the correct one.
---

Fixed issue #33

---

CONTRIBUTING.md

Issue Tracker Link Fixed

---

INSTALL.md

Issue #64 solved

---

CONTRIBUTING.md

Added a description and a gitflow link containing more concise explanation which could be useful for new developers.
This PR will resolve #78 
---

Added description and gitflow link to CONTRIBUTING.md file

---

INSTALL.md

Added Vbox recommendations

---

CONTRIBUTING.md
README.md

Added the FarmData2 Zulip discussion board for contact. And addd Zulip in acknowledgements since they have provided free cloud hosting.
---

Readmeupdate

---

CONTRIBUTING.md
README.md

Added links to the FarmData2 zulip and some information for new users who are unfamiliar with the app or who need a little boost in figuring it out.
---

added some info about Zulip

---

INSTALL.md

INSTALL now points out the use of the Theia IDE.
---

Added section to INSTALL about editing using browser based IDE

---

INSTALL.md
docker/theia/Dockerfile

Updated install process to:
- Silence error message about deleting user in build of Theia IDE container.
- Update instruction to extract db to not use sudo or preserve ownership of files.
---

Updated install process

---

.gitignore

Updated .gitignore to ignore Cypress and Theia files that don't need to be stored.
---

Added Theia and Cypress paths

---

INSTALL.md

Put section at bottom of INSTALL to give information about the phpMyAdmin service for those that might need it.
---

Added phpMyAdmin info

---

docker/docker-compose.yml

Added specific version tags to docker-compose to avoid any possibility of latest breaking something.  These can then be updated intentionally as necessary.
---

Added version tags to docker-compose images.

---

docker/docker-compose.yml

Fixed the non-functioning phpMyAdmin issue.
---

Switched phpMyAdmin to apache tag.

---

docker/docker-compose.yml
docker/farmOS/Dockerfile

FarmOS Dockerfile had incorrectly set the working directory.
---

Fixed farmOS container working directory

---

.gitignore
.theia/recentworkspace.json

I have added recentworkspace.json to gitignore file.
Fixes #118 
---

Exclude recentworkspace.json from git

---

INSTALL.md
ONBOARDING.md

Fix some typos in the documentation files INSTALL.md and ONBOARDING.md
---

Fix some typos in documentation files INSTALL.md and ONBOARDING.md

---

farmdata2_modules/fd2_tabs/fd2_barn_kit/fd2_barn_kit.module
farmdata2_modules/fd2_tabs/fd2_barn_kit/traySeedingReport.html

Draft Pull request that will update as @josieecook, @ShannonLoughin, and @Diego2214 complete their stories and tasks to complete the epic. The goal of the epic is to create a sub-tab in the Barn Kit tab of Farm Data 2 where a user can request a report of tray seeding logs specified by date, crop, etc.
---

Request Tray Seeding Report - Epic

---

.gitignore
farmdata2_modules/fd2_tabs/fd2_example/cypress/fixtures/example.json
farmdata2_modules/fd2_tabs/fd2_example/cypress/integration/example.spec.js
farmdata2_modules/fd2_tabs/fd2_example/cypress/integration/fd2vars.spec.js
farmdata2_modules/fd2_tabs/fd2_example/cypress/integration/visibility.spec.js
farmdata2_modules/fd2_tabs/fd2_example/ex1.html
farmdata2_modules/fd2_tabs/fd2_example/fd2_example.info
farmdata2_modules/fd2_tabs/fd2_example/test_runner.bash
farmdata2_modules/fd2_tabs/resources/fieldsDropdownComponent.js

This PR reformulates the Ex1 example in the fd2_example module to use a Vue Component just for illustration and testing purposes. 
---

Reformulated Ex1 using a vue Component

---

farmdata2_modules/cypress.json
farmdata2_modules/cypress/fixtures/example.json

Modified the cypress.json file in fd2_modules to omit screnshots and videos.  It is expected that at least for now most tests will be being run in the GUI and thus will be interactive. May come back later and add some flags to the runner.
---

Modified cypress configuration to omit screenshots and videos

---

ONBOARDING.md

Added some additional direct links to useful pages for writing cypress assertions and chainers.  These were in the original resources linked, but just give direct links to the most relevant and reused resoures.
---

Added more resource links for cypress

---

farmdata2_modules/fd2_tabs/fd2_example/README.md
farmdata2_modules/test_runner.bash

Adds documentation for end-to-end and component testing using the Cypress framework.
Closes #171 
---

Document Component Testing

---

CONTRIBUTING.md
INSTALL.md
ONBOARDING.md
farmdata2_modules/fd2_tabs/fd2_example/README.md

Documentation was updated in a number of locations to address the addition of Cypress component testing and to differentiate it from end-to-end testing.  Related to #171.
---

Documentation updated to Address Component Testing

---

farmdata2_modules/fd2_tabs/fd2_example/ex1.html
farmdata2_modules/fd2_tabs/fd2_example/ex1.spec.js
farmdata2_modules/fd2_tabs/fd2_example/fd2_example.info
farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.js
farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.spec.comp.js
farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.js
farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.spec.comp.js

Adds the DateSelectionComponent and DateRangeSelectionComponent to the fd2_tabs/resources folder.  Also provides component tests for each of the components.  They are added to the ex1.html sub-tab for demonstration purposes along with some e2e tests for that page.
This PR supersedes #180.

Adds DateSelectionComponent and DateRangeSelectionComponent

---

farmdata2_modules/fd2_tabs/fd2_example/ex1.html
farmdata2_modules/fd2_tabs/fd2_example/ex1.spec.js
farmdata2_modules/fd2_tabs/fd2_example/fd2_example.info
farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js
farmdata2_modules/fd2_tabs/resources/CustomTableComponent.spec.comp.js

Co-authored-by: josieecook <cookjo@dickinson.edu>
Co-authored-by: IrisSC <shakerci@dickinson.edu>
Custom table component that allows rows to be edited and deleted.  Table data is provided in props. Each edit or delete emits  and event identifying the change that can be processed by the page.  Component tests are included.  The component was also added to ex1.html for testing and demonstration.  E2e tests were added to ex1.spec.comp.js.
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the …

Added custom table component that supports editing and deleting of rows.

---

farmdata2_modules/fd2_tabs/fd2_example/ex1.html

Added a demonstration of how to delete a record by id from the database. The critical piece here is that it is necessary retrieve and use the session token when making any changes to the database through the restws module.
---

Adds delete record demo to ex1.html

---

farmdata2_modules/fd2_tabs/fd2_example/ex1.html

Improved the code in deleteLog by chaining then's instead of nesting them.  This is better javascript style and less error prone for error handling and synchronization issues.
---

Chained instead of nested thens in deleteLog

---

farmdata2_modules/fd2_tabs/resources/FarmOSAPI.js
farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js

Simplifies the getALLPages function and provides working Cypress tests to check a single and multipage response.  The tests will need to be updated when the new sample database is ready.  But for now they work.
---

Refines and Completes getAllPages

---

docker/sampleDB/buildSampleDB.bash

Updates the sample db image (docker/db.sample.tar.bz2) so that the FarmData2 modules (example, field kit, barn kit) are enabled.
---

Enable fd2 mods

---

farmdata2_modules/cypress/support/commands.js
farmdata2_modules/fd2_tabs/resources/FarmOSAPI.js
farmdata2_modules/fd2_tabs/resources/FarmOSAPI.spec.js

Fixes all of the unit tests for the functions in the FarmOSAPI.js file.  In addition, the api's of the functions were cleaned up and made more consistent and were documented with comments.
Closes #210 
Closes #212
---

Fixes Tests for FarmOSAPI.js Functions

---

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html
farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.spec.js

This should add the tests for the report disappearing in the page.
Solves #310 
---

Disappear page tests

---

farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.js
farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.spec.comp.js
farmdata2_modules/fd2_tabs/resources/README.md

Modifies the DropdownWithAllComponent so that changes to the defaultInput prop will change the value that is selected in the dropdown.  This allows the containing page to programmatically change the selected value.
Closes #319
---

Modifying defaultInput prop changes selected value

---

farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js
farmdata2_modules/fd2_tabs/resources/CustomTableComponent.spec.comp.js

CustomTableComponent now has unique data-cy attributes for each row, and each element of each row.  The tests have been refactored to use these attributes.
Resolves #354 
---

Refactored CustomTableComponent

---

farmdata2_modules/fd2_tabs/fd2_example/cache.spec.js
farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.js
farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.spec.comp.js

Patches a few failing tests in the FD2 Example tab.
---

FD2 Example Test Patches

---

INSTALL.md

fixed a typo in INSTALL.md
---

fix typo in INSTALL.md

---

INSTALL.md

fixed typo in email address
---

fixed typo in email address

---

farmdata2_modules/fd2_tabs/fd2_school/README.md
farmdata2_modules/fd2_tabs/resources/FarmOSAPI.js

fixing 2 typos

---

INSTALL.md

Added the missing information as reported in issue:
https://github.com/DickinsonCollege/FarmData2/issues/101
---

Issue-101: Updated instructions on install.md

---

docker/setDB.bash

fix typo in setDB.bash

---

farmdata2_modules/fd2_tabs/fd2_example/README.md

fix typos in fd2_example/README.md
---

Typo fixes in fd2_example/README.md

---

ONBOARDING.md

fix typos in ONBOARDING.md
---

fix typos in ONBOARDING.md

---

farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js

fix typos in CustomTableComponent.js
---

fix typos in CustomTableComponent.js

---

farmdata2_modules/fd2_tabs/fd2_example/api.html
farmdata2_modules/fd2_tabs/fd2_example/api.spec.js
farmdata2_modules/fd2_tabs/fd2_example/maps.html
farmdata2_modules/fd2_tabs/resources/FarmOSAPI.js

Fixes #422 
In addition, this PR makes a few other small updates to the Examples.
* Added a test for clearing the seeding logs
* Added a comment to FarmOSAPI.js to clarify the parsing of the data field.
* Updated text in the "Maps" example page to point to the documentation.
---

Fix Bug in API Example 

---

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html

Resolves #471. Fixes some capitalization inconsistencies concerning table headers. Also swaps the 'Hours' and 'Workers' columns in the table to more clearly demonstrate that the hours column represents the total amount of hours worked and not the number of hours worked per worker.
---

Seeding Report Edits

---

farmdata2_modules/fd2_tabs/resources/DateRangeSelectionComponent.spec.comp.js

Removed the mounting in the context to be in the individual tests since each test is mounting for its own purposes anyway making the mounting in the context redundant and unnecessary. 
---

DateRangeSelection: Fixed Cypress Test

---

farmdata2_modules/fd2_tabs/resources/DateSelectionComponent.spec.comp.js

Removed the mounting in the context to be in the individual tests since each test is mounting for its own purposes anyway making the mounting in the context redundant and unnecessary.
---

DateSelection: Fixed Cypress Test

---

farmdata2_modules/fd2_tabs/resources/DropdownWithAllComponent.spec.comp.js

Removed the mounting in the context to be in the individual tests since each test is mounting for its own purposes anyway making the mounting in the context redundant and unnecessary.
---

DropdownWithAll: Fixed Cypress Test

---

.gitignore
farmdata2_modules/fd2_tabs/fd2_example/api.spec.js

Closes #505 
Updates to typo and grammar inside the api.spec.js file. 
Updated .gitignore file to ignore .idea files to allow dev using Jetbrain IDEs.
---

[505] typo grammar updates

---

.gitignore
farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.html
farmdata2_modules/fd2_tabs/fd2_field_kit/seedingInput.spec.js

Fixes #368. Refactored the cypress test file for the new seeding input form. Some minor bugs in the input form have been fixed as well. 
---

Issue #368 seeding input e2e cypress test

---

farmdata2_modules/fd2_tabs/fd2_barn_kit/seedingReport.html
farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js
farmdata2_modules/fd2_tabs/resources/CustomTableComponent.spec.comp.js

This pull request aims to resolve issue #290. It addresses this issue by adding an export functionality to the [CustomTableComponent.js](https://github.com/FarmData-2-Dev-Team-2022/FarmData2/blob/CSVExport/farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js) file. 
**Note: This PR is incomplete and progress is ongoing.**
These are steps that need to be completed prior to making this PR available to review:
--- …

CustomTableComponent: Adding Export Functionality

---

farmdata2_modules/fd2_tabs/resources/RegexInputComponent.js
farmdata2_modules/fd2_tabs/resources/RegexInputComponent.spec.comp.js

Fixes #543 Added watch for regex component.
---

Issue543 regex input component watch regex

---

farmdata2_modules/fd2_tabs/resources/CustomTableComponent.js

Closes #559. Fixed an issue where not all commas were being removed from the comments value. 
---

Changed all the Replace Functions to ReplaceAlls to Capture Everything

---

docker/dev/Dockerfile
farmdata2_modules/fd2_tabs/resources/JSDoc.json
farmdata2_modules/fd2_tabs/resources/README.md
farmdata2_modules/fd2_tabs/resources/doc.bash

Patch Dev Container to ensure JSDoc and its Vue Dependencies are installed.

---

docker/dev/Dockerfile

Configured git for meld with diff3.
Pinned versions of Cypress tools. 
---

Dev cont patches

---

INSTALL.md

* Fixed some small typos.
* Added a line about waiting and retrying if the TigerVNC Viewer quits does not connect immediately.
---

Updated INSTALL.md - fixed typos

---

docker/dev/Dockerfile
docker/dev/startup.bash

Added the chromium browser to the image.  This browser is not very usable on its own in the dev_container due to some issues with chromium running in a docker container.  However, it works very well with the Cypress testing application.  So it is installed for that purpose.
This PR also ensures that the dbus daemon is running which resolves many (though not all) issues with running gui applications that uses dbus from the command line.
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the …

Added Chromium browser to image

---

farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.html
farmdata2/farmdata2_modules/fd2_barn_kit/transplantingReport/transplantingReport.html

Closes #539. This branch uncomments some pre-existing code that already set the date to the first day of the year. 
---

Report Pages: Updating Default Date

---

docker/fd2-up.bash

Quoted path in fd2_up.bash to allow spaces

---

docker/dev/repo.txt
docker/docker-compose.yml

New BannerComponent needs some JSDoc plugins for doc generation.
---

Bump the dev container version

---

docker/dev/Dockerfile
docker/dev/repo.txt
docker/docker-compose.yml
farmdata2/cypress/support/component.js

Reverts DickinsonCollege/FarmData2#652

Revert "Add Bootstrap support to Vue Component Tests"

---

docker/dev/Dockerfile
docker/dev/repo.txt
docker/docker-compose.yml
farmdata2/cypress/support/component.js

Builds on #649.  See that PR for a fuller description.
Closes #649.
---

Add Bootstrap support to Vue Component Tests

---

farmdata2/farmdata2_modules/cypress/fd2tabs.existence.spec.js

…l/228
Link to the original pull request: [#288](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/228)
Authors of the original Commit are listed here as co-Authors:
Co-authored-by: jamesng5 <nguyenja@dickinson.edu>
Co-authored-by: vuphuongha <havu0910@gmail.com>
Co-authored-by: tainguyen103 <tainguyen103200@gmail.com>
Partially Addresses #662
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms …

Migrates: Main fd2 tabs test #228

---

farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js

Co-authored-by: nathang15 <nguyenat@dickinson.edu>
Co-authored-by: infantlikesprogramming <hadu@dickinson.edu>
Link to the original pull request: [210](https://github.com/DickinsonCollege/FD2School-FarmData2/pull/210)
--- …

Migrates: Test Barn Kit Seeding Report columns by seeding type #210

---

farmdata2/farmdata2_modules/resources/CustomTableComponent.js

Co-authored-by: pranavm2109 <mishrap@dickinson.edu>
Link to the original pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/239
---

Migrates: edited documentation in lines 33 and 34 of CustomTableComponent (#239)

---

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.submit.button.spec.js

Co-authored-by: Foogabob <locker@dickinson.edu>
Co-authored-by: EliasBerhe <eliastes123@gmail.com>
Link to the original pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/208
--- …

Migrates: Seeding Input: Tests for Submit Button Behavior (#208)

---

farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js

Co-authored-by: andrewscheiner53 <scheinea@dickinson.edu>
Co-authored-by: pranavm2109 <mishrap@dickinson.edu>
Link to the original pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/196
--- …

Migrates: Tested the Seeding Report Crop Filter (#196)

---

farmdata2/farmdata2_modules/fd2_barn_kit/transplantingReport/transplantingReport.defaults.spec.js
farmdata2/farmdata2_modules/fd2_barn_kit/transplantingReport/transplantingReport.html

* Added spec.js file for testing transplating report
* Tested page header and section label
* Tested if the generate button has correct value and is enabled
* The report table is not visible
* Tested default start, end dates using dayjs
* Changed data-cy atrribute name for - Set Dates
* click() is removed when getting the default dates
* Made final changes for the test
* Made final changes to the test
Link to the original pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/197
---
FarmData2 is a [Free Cultural …

Migrates: Testing Transplanting Report Defaults (#197)

---

farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js
farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html

* Initial commit, adding seeding input data cypress test
* subtask #1 Assert header has 'Data'
* Check the crop dropdown list size
* Testing crop dropdown
* Testing for crop dropdown length
* Testing for crop dropdown length
* test input date element enabled and has correct default value
* Created test to check if crop selected has been enabled
* Cleaning cypress test
* Add test to check if any option was selected
* Remove dropdown element reference via children function
* combined similar 'it' blocks
* Created test to check that the crop drop down does not have a selected value
Co-authored-by: nathang15 <nguyenat@dickinson.edu>
Co-authored-by: infantlikesprogramming <hadu@dickinson.edu>
---------
This pull request was orignially created on …

Migrates: Initial commit, adding seeding input data cypress test (#175)

---

farmdata2/C:UsersrolanDocumentsDicksinson-SSD-FolderCOMP-290fd2School.txt
farmdata2/C:UsersrolanOneDriveDocumentsDickinsonWork2023-2024fd2School.txt
farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.default.spec.js
farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.html

* updated fd2 branch + tests
* Updated tests
* test for Barn-Kit seeding report default
* updated tests
* updated tests
* "Made minor corrections to tests"
>
>
Co-authored-by: Sai Atluri <atluris@dickinson.edu>
* Updated date selection header test
* Updated date selection header test
* Corrected minor minor merging error
* Fixed formatting
Co-authored-by: Melantha-Chen <yuxuan.chen.1031@outlook.com>
This pull request was originally created on [FD2School-FarmData2](https://github.com/DickinsonCollege/FD2School-FarmData2).
Link to the original pull request: https://github.com/DickinsonCollege/FD2School-FarmData2/pull/227
---
FarmData2 is a [Free Cultural …

Migrates: 227 testing the default values of the seeding report

---

docker/dev/startup.bash

As part of my crusade to resolve #655, the actual dev container script is going to take some time to analyze but I figured I would start with the smallest fish and take a look at the actual startup script inside the dev container. I mostly reworded some of the comments to be clearer and used a single 'sudo' command with a here-document to reduce footprint. It's a small portion, I would imagine it will take a while to actually speed up the container but every little bit helps!
---
FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I …

Refactored dev/startup.bash Docker container

---

INSTALL.md

Fixed a small typo in the installation instructions.
---

fixed small typo
